 GNU nano 6.4                   polybar_weather.sh                             
# Register at https://openweathermap.org to get your API key
# If you don't want to write your key here, you can delete this line and use th>
api_key = "ca0f7e1744f9ecc464a9ec1b02fd191a"

# This is for Montreal, find your city at https://openweathermap.org
# The id will be the last part of the URL
city_id = "2746300"

# Output format, using Handlebars syntax, meaning variables should be used like>
# Available tokens are:
temp_celcius
# - temp_kelvin
# - temp_fahrenheit
# - temp_icon
# - trend
# - forecast_celcius
# - forecast_kelvin
# - forecast_fahrenheit
# - forecast_icon
display = "{{ temp_celcius }}°C"



